In [1]:
import tensorflow as tf
from tensorflow import keras
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

In [2]:
# constant tensor
x = tf.constant([[5, 2], [1, 3]])
print(x)

tf.Tensor(
[[5 2]
 [1 3]], shape=(2, 2), dtype=int32)


In [3]:
x.numpy()

array([[5, 2],
       [1, 3]], dtype=int32)

In [4]:
print("dtype:", x.dtype)
print("shape:", x.shape)

dtype: <dtype: 'int32'>
shape: (2, 2)


In [5]:
print(tf.ones(shape=(2, 1)))
print(tf.zeros(shape=(2, 1)))

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)


In [6]:
x = tf.random.normal(shape=(2, 2), mean=0.0, stddev=1.0)

x = tf.random.uniform(shape=(2, 2), minval=0, maxval=10, dtype="int32")

In [7]:
initial_value = tf.random.normal(shape=(2, 2))
a = tf.Variable(initial_value)
print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 1.808719  ,  0.47483763],
       [-0.2656816 , -0.9566678 ]], dtype=float32)>


In [8]:
new_value = tf.random.normal(shape=(2, 2))
a.assign(new_value)
for i in range(2):
    for j in range(2):
        assert a[i, j] == new_value[i, j]

added_value = tf.random.normal(shape=(2, 2))
a.assign_add(added_value)
for i in range(2):
    for j in range(2):
        assert a[i, j] == new_value[i, j] + added_value[i, j]

In [9]:
a = tf.random.normal(shape=(2, 2))
b = tf.random.normal(shape=(2, 2))

c = a + b
d = tf.square(c)
e = tf.exp(d)

# Neural Network

In [38]:
import numpy as np
path_to_mnist_npz = '/Users/biancaleoveanu/Downloads/mnist.npz' 
with np.load(path_to_mnist_npz, allow_pickle=True) as data:
    X_train, y_train = data['x_train'], data['y_train']
    X_test, y_test = data['x_test'], data['y_test']


In [39]:
from keras.models import Sequential
from keras.layers import Input, Flatten, Dense

In [40]:

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)), # Images are 28x28 px
  tf.keras.layers.Dense(64, activation='relu'), # Hidden layer
  tf.keras.layers.Dense(64, activation='relu'),                  # Normalization layer
  tf.keras.layers.Dense(10, activation='softmax')# There are 10 classes
])

In [41]:
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate= 0.001),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [42]:
model.fit(X_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 402us/step - accuracy: 0.7685 - loss: 4.6574
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 417us/step - accuracy: 0.9156 - loss: 0.3426
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 414us/step - accuracy: 0.9377 - loss: 0.2316
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 413us/step - accuracy: 0.9470 - loss: 0.1920
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 404us/step - accuracy: 0.9551 - loss: 0.1576


In [43]:
# Evaluate the model on the test data using `evaluate`
print("Evaluate on test data")
results = model.evaluate(X_test, y_test, batch_size=128)
print("test loss, test acc:", results)

Evaluate on test data
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 386us/step - accuracy: 0.9445 - loss: 0.1998
test loss, test acc: [0.172510027885437, 0.9526000022888184]


# Experiment

## 7 layers, 64 neurons

### LR=0.001

In [61]:

model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)), # Images are 28x28 px
    tf.keras.layers.Dense(64, activation='relu'), # Hidden layer
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(64, activation='relu'),  
    tf.keras.layers.Dense(64, activation='relu'),  
    tf.keras.layers.Dense(64, activation='relu'),  # Normalization layer
    tf.keras.layers.Dense(10, activation='softmax')# There are 10 classes
])

In [62]:
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate= 0.001),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [63]:
model.fit(X_train, y_train, epochs=3)

Epoch 1/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 506us/step - accuracy: 0.7607 - loss: 1.3088
Epoch 2/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 504us/step - accuracy: 0.9397 - loss: 0.2104
Epoch 3/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 506us/step - accuracy: 0.9540 - loss: 0.1602


In [64]:
# Evaluate the model on the test data using `evaluate`
print("Evaluate on test data")
results = model.evaluate(X_test, y_test, batch_size=128)
print("test loss, test acc:", results)

Evaluate on test data
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 450us/step - accuracy: 0.9430 - loss: 0.1850
test loss, test acc: [0.15615186095237732, 0.9524999856948853]


### LR=0.0025

In [65]:

model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)), # Images are 28x28 px
    tf.keras.layers.Dense(64, activation='relu'), # Hidden layer
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(64, activation='relu'),  
    tf.keras.layers.Dense(64, activation='relu'),  
    tf.keras.layers.Dense(64, activation='relu'),  # Normalization layer
    tf.keras.layers.Dense(10, activation='softmax')# There are 10 classes
])
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate= 0.0025),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
model.fit(X_train, y_train, epochs=3)

Epoch 1/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 514us/step - accuracy: 0.7762 - loss: 1.3548
Epoch 2/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 500us/step - accuracy: 0.9333 - loss: 0.2402
Epoch 3/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 498us/step - accuracy: 0.9454 - loss: 0.2022


In [66]:
# Evaluate the model on the test data using `evaluate`
print("Evaluate on test data")
results = model.evaluate(X_test, y_test, batch_size=128)
print("test loss, test acc:", results)

Evaluate on test data
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 466us/step - accuracy: 0.9413 - loss: 0.2403
test loss, test acc: [0.21349479258060455, 0.9473000168800354]


### LR=0.003

In [67]:

model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)), # Images are 28x28 px
    tf.keras.layers.Dense(64, activation='relu'), # Hidden layer
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(64, activation='relu'),  
    tf.keras.layers.Dense(64, activation='relu'),  
    tf.keras.layers.Dense(64, activation='relu'),  # Normalization layer
    tf.keras.layers.Dense(10, activation='softmax')# There are 10 classes
])
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate= 0.003),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
model.fit(X_train, y_train, epochs=3)

Epoch 1/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 498us/step - accuracy: 0.7917 - loss: 1.2558
Epoch 2/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 493us/step - accuracy: 0.9289 - loss: 0.2622
Epoch 3/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 511us/step - accuracy: 0.9397 - loss: 0.2296


In [68]:
# Evaluate the model on the test data using `evaluate`
print("Evaluate on test data")
results = model.evaluate(X_test, y_test, batch_size=128)
print("test loss, test acc:", results)

Evaluate on test data
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 471us/step - accuracy: 0.9396 - loss: 0.2435
test loss, test acc: [0.2056094855070114, 0.9488000273704529]


## 7 layers, 100 neurons

### LR=0.001

In [78]:

model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)), # Images are 28x28 px
    tf.keras.layers.Dense(100, activation='relu'), # Hidden layer
    tf.keras.layers.Dense(100, activation='relu'),
    tf.keras.layers.Dense(100, activation='relu'),  
    tf.keras.layers.Dense(100, activation='relu'),  
    tf.keras.layers.Dense(100, activation='relu'),  # Normalization layer
    tf.keras.layers.Dense(10, activation='softmax')# There are 10 classes
])
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate= 0.001),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
model.fit(X_train, y_train, epochs=3)

Epoch 1/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 715us/step - accuracy: 0.7941 - loss: 1.2610
Epoch 2/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 707us/step - accuracy: 0.9443 - loss: 0.1958
Epoch 3/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 710us/step - accuracy: 0.9586 - loss: 0.1476


In [79]:
# Evaluate the model on the test data using `evaluate`
print("Evaluate on test data")
results = model.evaluate(X_test, y_test, batch_size=128)
print("test loss, test acc:", results)

Evaluate on test data
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 600us/step - accuracy: 0.9489 - loss: 0.1797
test loss, test acc: [0.1521594077348709, 0.9564999938011169]


### LR=0.0025

In [80]:

model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)), # Images are 28x28 px
    tf.keras.layers.Dense(100, activation='relu'), # Hidden layer
    tf.keras.layers.Dense(100, activation='relu'),
    tf.keras.layers.Dense(100, activation='relu'),  
    tf.keras.layers.Dense(100, activation='relu'),  
    tf.keras.layers.Dense(100, activation='relu'),  # Normalization layer
    tf.keras.layers.Dense(10, activation='softmax')# There are 10 classes
])
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate= 0.0025),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
model.fit(X_train, y_train, epochs=3)

Epoch 1/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 722us/step - accuracy: 0.8184 - loss: 1.0814
Epoch 2/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 720us/step - accuracy: 0.9363 - loss: 0.2303
Epoch 3/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 712us/step - accuracy: 0.9473 - loss: 0.1957


In [81]:
# Evaluate the model on the test data using `evaluate`
print("Evaluate on test data")
results = model.evaluate(X_test, y_test, batch_size=128)
print("test loss, test acc:", results)

Evaluate on test data
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 616us/step - accuracy: 0.9417 - loss: 0.2425
test loss, test acc: [0.2114408165216446, 0.9491000175476074]


### LR=0.003

In [82]:

model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)), # Images are 28x28 px
    tf.keras.layers.Dense(100, activation='relu'), # Hidden layer
    tf.keras.layers.Dense(100, activation='relu'),
    tf.keras.layers.Dense(100, activation='relu'),  
    tf.keras.layers.Dense(100, activation='relu'),  
    tf.keras.layers.Dense(100, activation='relu'),  # Normalization layer
    tf.keras.layers.Dense(10, activation='softmax')# There are 10 classes
])
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate= 0.003),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
model.fit(X_train, y_train, epochs=3)

Epoch 1/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 722us/step - accuracy: 0.7974 - loss: 1.4608
Epoch 2/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 709us/step - accuracy: 0.9326 - loss: 0.2447
Epoch 3/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 720us/step - accuracy: 0.9448 - loss: 0.2126


In [83]:
# Evaluate the model on the test data using `evaluate`
print("Evaluate on test data")
results = model.evaluate(X_test, y_test, batch_size=128)
print("test loss, test acc:", results)

Evaluate on test data
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 597us/step - accuracy: 0.9366 - loss: 0.2636
test loss, test acc: [0.23321697115898132, 0.9409999847412109]


## 10 layers, 64 neurons

### LR=0.001

In [76]:

model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)), # Images are 28x28 px
    tf.keras.layers.Dense(64, activation='relu'), # Hidden layer
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(64, activation='relu'),  
    tf.keras.layers.Dense(64, activation='relu'),  
    tf.keras.layers.Dense(64, activation='relu'), 
    tf.keras.layers.Dense(64, activation='relu'), 
    tf.keras.layers.Dense(64, activation='relu'), 
    tf.keras.layers.Dense(64, activation='relu'),  # Normalization layer
    tf.keras.layers.Dense(10, activation='softmax')# There are 10 classes
])
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate= 0.001),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
model.fit(X_train, y_train, epochs=3)

Epoch 1/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 642us/step - accuracy: 0.7895 - loss: 0.7698
Epoch 2/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 620us/step - accuracy: 0.9426 - loss: 0.2003
Epoch 3/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 628us/step - accuracy: 0.9565 - loss: 0.1599


In [77]:
# Evaluate the model on the test data using `evaluate`
print("Evaluate on test data")
results = model.evaluate(X_test, y_test, batch_size=128)
print("test loss, test acc:", results)

Evaluate on test data
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 510us/step - accuracy: 0.9391 - loss: 0.2115
test loss, test acc: [0.18576781451702118, 0.946399986743927]


### LR=0.0025

In [84]:

model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)), # Images are 28x28 px
    tf.keras.layers.Dense(64, activation='relu'), # Hidden layer
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(64, activation='relu'),  
    tf.keras.layers.Dense(64, activation='relu'),  
    tf.keras.layers.Dense(64, activation='relu'), 
    tf.keras.layers.Dense(64, activation='relu'), 
    tf.keras.layers.Dense(64, activation='relu'), 
    tf.keras.layers.Dense(64, activation='relu'),  # Normalization layer
    tf.keras.layers.Dense(10, activation='softmax')# There are 10 classes
])
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate= 0.0025),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
model.fit(X_train, y_train, epochs=3)

Epoch 1/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 621us/step - accuracy: 0.7986 - loss: 0.8047
Epoch 2/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 612us/step - accuracy: 0.9389 - loss: 0.2398
Epoch 3/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 615us/step - accuracy: 0.9503 - loss: 0.2044


In [85]:
# Evaluate the model on the test data using `evaluate`
print("Evaluate on test data")
results = model.evaluate(X_test, y_test, batch_size=128)
print("test loss, test acc:", results)

Evaluate on test data
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 497us/step - accuracy: 0.9413 - loss: 0.2432
test loss, test acc: [0.20930352807044983, 0.9501000046730042]


### LR=0.003

In [86]:

model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)), # Images are 28x28 px
    tf.keras.layers.Dense(64, activation='relu'), # Hidden layer
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(64, activation='relu'),  
    tf.keras.layers.Dense(64, activation='relu'),  
    tf.keras.layers.Dense(64, activation='relu'), 
    tf.keras.layers.Dense(64, activation='relu'), 
    tf.keras.layers.Dense(64, activation='relu'), 
    tf.keras.layers.Dense(64, activation='relu'),  # Normalization layer
    tf.keras.layers.Dense(10, activation='softmax')# There are 10 classes
])
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate= 0.003),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
model.fit(X_train, y_train, epochs=3)

Epoch 1/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 584us/step - accuracy: 0.7891 - loss: 0.7383
Epoch 2/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 591us/step - accuracy: 0.9366 - loss: 0.2502
Epoch 3/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 591us/step - accuracy: 0.9459 - loss: 0.2169


In [87]:
# Evaluate the model on the test data using `evaluate`
print("Evaluate on test data")
results = model.evaluate(X_test, y_test, batch_size=128)
print("test loss, test acc:", results)

Evaluate on test data
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 505us/step - accuracy: 0.9437 - loss: 0.2258
test loss, test acc: [0.19912506639957428, 0.9491000175476074]


## 10 layers, 100 neurons

### LR=0.001

In [91]:

model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)), # Images are 28x28 px
    tf.keras.layers.Dense(100, activation='relu'), # Hidden layer
    tf.keras.layers.Dense(100, activation='relu'),
    tf.keras.layers.Dense(100, activation='relu'),  
    tf.keras.layers.Dense(100, activation='relu'),  
    tf.keras.layers.Dense(100, activation='relu'),
    tf.keras.layers.Dense(100, activation='relu'),
    tf.keras.layers.Dense(100, activation='relu'),
    tf.keras.layers.Dense(100, activation='relu'),  # Normalization layer
    tf.keras.layers.Dense(10, activation='softmax')# There are 10 classes
])
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate= 0.001),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
model.fit(X_train, y_train, epochs=3)

Epoch 1/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 887us/step - accuracy: 0.8132 - loss: 0.7134
Epoch 2/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 888us/step - accuracy: 0.9487 - loss: 0.1846
Epoch 3/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 920us/step - accuracy: 0.9613 - loss: 0.1474


In [92]:
# Evaluate the model on the test data using `evaluate`
print("Evaluate on test data")
results = model.evaluate(X_test, y_test, batch_size=128)
print("test loss, test acc:", results)

Evaluate on test data
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 775us/step - accuracy: 0.9509 - loss: 0.2094
test loss, test acc: [0.17413723468780518, 0.9584000110626221]


### LR=0.003

In [93]:

model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)), # Images are 28x28 px
    tf.keras.layers.Dense(100, activation='relu'), # Hidden layer
    tf.keras.layers.Dense(100, activation='relu'),
    tf.keras.layers.Dense(100, activation='relu'),  
    tf.keras.layers.Dense(100, activation='relu'),  
    tf.keras.layers.Dense(100, activation='relu'),
    tf.keras.layers.Dense(100, activation='relu'),
    tf.keras.layers.Dense(100, activation='relu'),
    tf.keras.layers.Dense(100, activation='relu'),  # Normalization layer
    tf.keras.layers.Dense(10, activation='softmax')# There are 10 classes
])
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate= 0.003),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
model.fit(X_train, y_train, epochs=3)

Epoch 1/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 877us/step - accuracy: 0.8110 - loss: 0.8036
Epoch 2/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 919us/step - accuracy: 0.9408 - loss: 0.2406
Epoch 3/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 900us/step - accuracy: 0.9498 - loss: 0.2137


In [94]:
# Evaluate the model on the test data using `evaluate`
print("Evaluate on test data")
results = model.evaluate(X_test, y_test, batch_size=128)
print("test loss, test acc:", results)

Evaluate on test data
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 729us/step - accuracy: 0.9532 - loss: 0.2102
test loss, test acc: [0.19643403589725494, 0.9563999772071838]


### LR=0.005

In [95]:

model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)), # Images are 28x28 px
    tf.keras.layers.Dense(100, activation='relu'), # Hidden layer
    tf.keras.layers.Dense(100, activation='relu'),
    tf.keras.layers.Dense(100, activation='relu'),  
    tf.keras.layers.Dense(100, activation='relu'),  
    tf.keras.layers.Dense(100, activation='relu'),
    tf.keras.layers.Dense(100, activation='relu'),
    tf.keras.layers.Dense(100, activation='relu'),
    tf.keras.layers.Dense(100, activation='relu'),  # Normalization layer
    tf.keras.layers.Dense(10, activation='softmax')# There are 10 classes
])
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate= 0.005),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
model.fit(X_train, y_train, epochs=3)

Epoch 1/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 874us/step - accuracy: 0.7838 - loss: 0.9608
Epoch 2/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 899us/step - accuracy: 0.9175 - loss: 0.3378
Epoch 3/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 871us/step - accuracy: 0.9226 - loss: 0.3266


In [96]:
# Evaluate the model on the test data using `evaluate`
print("Evaluate on test data")
results = model.evaluate(X_test, y_test, batch_size=128)
print("test loss, test acc:", results)

Evaluate on test data
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 700us/step - accuracy: 0.8733 - loss: 0.5437
test loss, test acc: [0.46874430775642395, 0.8907999992370605]


In [99]:
model.save('Models/mnist.keras')